[SAFRAN-1080]Use Mylyn 3.26.1 from Eclipse 2023-06 in target platform
S@fran studio is based on OD Team 11.7.1 which is based on Eclipse
2021-06. So far we've been using Mylyn version 3.25.2 pulled down by OD
Team 11.7.1.

But this version is causing some issue due to
https://bugs.eclipse.org/bugs/show_bug.cgi?id=569078 where, essentially,
due to a missing version constraint on imported packages, we can easily
end up with a broken S@fran studio where Java package 'javax.xml.bind'
is provided by both bundles 'javax.xml.bind v2.2.0' and
'jakarta.xml.bind v2.3.3'. Usually this broken state happens after
installing from some additional update sites, e.g. Mylyn Wikitext from
Eclipse Simrel 2021-06.

Once in this broken state, the most noticeable impact is that
launching a runtime Eclipse application takes a LONG time, and in the
console Eclipse complains about the dependency resolution as follows:
Bundle was not resolved because of a uses constraint violation.
org.apache.felix.resolver.reason.ReasonException: Uses constraint
violation. Unable to resolve resource
org.eclipse.mylyn.commons.notifications.feed [osgi.identity;
osgi.identity="org.eclipse.mylyn.commons.notifications.feed";
type="osgi.bundle"; version:Version="1.18.0.v20190930-2131";
singleton:="true"] because it is exposed to package 'javax.xml.bind'
from resources javax.xml.bind [osgi.identity;
osgi.identity="javax.xml.bind"; type="osgi.bundle";
version:Version="2.2.0.v201105210648"] and jakarta.xml.bind
[osgi.identity; osgi.identity="jakarta.xml.bind"; type="osgi.bundle";
version:Version="2.3.3.v20221203-1659"] via two dependency chains.

Moreover it is a bit difficult to work on this bug because installing
from some p2 repositories is broken in Eclipse 2021-06, see
https://bugs.eclipse.org/bugs/show_bug.cgi?id=575541 - to circumvent
this, one must add to the target platform the desired dependency and
then repackage it in the S@fran update site. This way the dependency is
installable via the locally-build S@fran update site.

The originating bug has been fixed in Mylyn 3.26.1 which is provided by
Eclipse Simrel 2023-06 so we now include this version of Mylyn in the
Target Platform.
Note that this version of Mylyn pulls down org.apache.lucene 9.5.0 which
has import-package constraints to java.lang, java.io, etc., which is
also broken in Eclipse 2021-06 according to
https://bugs.eclipse.org/bugs/show_bug.cgi?id=580618 (and fixed in
Eclipse 2022-09). These extraneous, but inconsequential, dependency
validation errors occur upon launching a runtime Eclipse application.